// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaYPuLcTVtjZpptXJmtamfEyOyhGXF0Jg',
    appId: '1:913565307203:web:40e7ff181c4d2628169ff6',
    messagingSenderId: '913565307203',
    projectId: 'degilib',
    authDomain: 'degilib.firebaseapp.com',
    storageBucket: 'degilib.appspot.com',
    measurementId: 'G-M2CF15R1QH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-8IZboxjkxCSFcec0P414IgsiN9dkVnI',
    appId: '1:913565307203:android:c53f9084ddf9c4f0169ff6',
    messagingSenderId: '913565307203',
    projectId: 'degilib',
    storageBucket: 'degilib.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwcdyYRPo4tkqCCHsHouYD96wgh_9MHZk',
    appId: '1:913565307203:ios:a3a588167d565c0f169ff6',
    messagingSenderId: '913565307203',
    projectId: 'degilib',
    storageBucket: 'degilib.appspot.com',
    iosClientId: '913565307203-pj8oq6ps04cmomhcps8io6ll79hr16og.apps.googleusercontent.com',
    iosBundleId: 'com.srivats.degilib',
  );
}
